### PR TITLE
Fix for memory leak I reported in issue #45

### PR DESCRIPTION
**Pull request by AlexisH**
disclaimer: This is my very first line of code in C so take this change cautiously.
It solved the issue for my use case and that's all I can say :)

### CODE REVIEW

**Comment by kamakazikamikaze** [comment]
This appears to follow the format in other loops where `while (varlist_iter && (varbind = PyIter_Next(varlist_iter)))` occurs. I will see if I can find the files I used for testing my `bulkwalk` refactor and determine if this fixes the warnings thrown by Valgrind.

@AlexisH Good job! It may be too early to celebrate but if this worked for you, I am confident that this may be the fix to the leak :D

**Comment by kamakazikamikaze** [comment]
Ok, Valgrind actually shows that this does _not_ fix the leak (sadly). In my test results under #45 I found that the blocks that are "definitely lost" _are_, in fact, caused by `netsnmp_walk` and continue to persist even through this code change.

**Comment by AlexisH** [comment]
Since I included this patch on my server I do see a difference in memory usage over time, and looking into the gc module after calling gc.collect() no longer shows any object count constantly rising.

That being said my process still seems to be leaking - although not as much as before. But I can't tell for sure yet if what remains is still related to easysnmp.

Could it be that this change just hides things from the gc module?
Thanks for looking into it anyway.

**Comment by kamakazikamikaze** [comment]
I believe that your change _does_ fix an issue with counters not being decremented properly, thereby allowing the GC to correctly `free` them when they are no longer in scope/use. However, it doesn't fix _all_ of the issues with leaks.

I think I know what line(s) are causing the leak, however I'm not fully sure as to _why_ they're causing a leak. I'm going to test some changes. I updated the issue with comments on where I believe the underlying problem actually is.

**Comment by kamakazikamikaze** [comment]
@AlexisH Could you provide some of the code you use (for checking counters and memory size) or the details of how you're performing these checks in the open issue ticket? I'd like to coordinate more if possible :)

**Comment by kamakazikamikaze** [comment]
Superseded by #142

**Pull request closed without merging**
